jdbc:
  datasource:
    driverClass: com.mysql.cj.jdbc.Driver
    user: root
    password: 123456
    jdbcUrl: jdbc:mysql://localhost:3306/crm
    maxPoolSize: 100
    minPoolSize: 10
    initialPoolSize: 10

mybatis:
  type-aliases-package: com.hwua.pojo
  mapper-locations: classpath:com/hwua/mapper/*.xml

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

pagehelper:
  auto-dialect: mysql
  reasonable: true